export const INTERVIEW_ROUTES = {
  SCHEDULE: "/",
  GET_INTERVIEWS: "/",
  GET_INTERVIEW_DETAILS: "/:interviewId",
  RESCHEDULE: "/:interviewId/reschedule",
  CANCEL: "/:interviewId/cancel",
  START: "/:interviewId/start",
  END: "/:interviewId/end",
  JOIN: "/:interviewId/join",
  ACCEPT: "/:interviewId/accept",
  REJECT: "/:interviewId/reject",
  REQUEST_RESCHEDULE: "/:interviewId/request-reschedule",
  ACCEPT_RESCHEDULE: "/:interviewId/approve-reschedule",
  REJECT_RESCHEDULE: "/:interviewId/reject-reschedule",
} as const;
