export const NOTIFICATION_ERROR = {
    RECIPIENT_ID_REQUIRED : "RECIPIENT_ID_REQUIRED",
    TITLE_REQUIRED : "TITLE_REQUIRED",
    MESSAGE_REQUIRED : "MESSAGE_REQUIRED"

} as const;

export type UserErrorCode = (typeof NOTIFICATION_ERROR)[keyof typeof NOTIFICATION_ERROR];