export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS : "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  CANDIDATE_PROFILE_NOT_FOUND : "CANDIDATE_PROFILE_NOT_FOUND",
} as const;

export type ErrorCode =
  typeof ERROR_CODES[keyof typeof ERROR_CODES];
