export const DOMAIN_ERROR_CODES = {
  EMAIL_UPDATE_NOT_ALLOWED: "EMAIL_UPDATE_NOT_ALLOWED",
  PASSWORD_CHANGE_NOT_ALLOWED: "PASSWORD_CHANGE_NOT_ALLOWED",
  LOCAL_USER_MUST_HAVE_PASSWORD: "LOCAL_USER_MUST_HAVE_PASSWORD",
  GOOGLE_USER_MUST_HAVE_GOOGLE_ID: "GOOGLE_USER_MUST_HAVE_GOOGLE_ID",
  GOOGLE_USER_CANNOT_HAVE_PASSWORD: "GOOGLE_USER_CANNOT_HAVE_PASSWORD",
  USER_ID_REQUIRED : "USER_ID_REQUIRED",
  EXPIRY_TOKEN_MUST_BE_IN_FUTURE : "EXPIRY_TOKEN_MUST_BE_IN_FUTURE"
} as const;
