export const DOMAIN_ERRORS = {
   TEMPLATE_ALREADY_INACTIVE: "TEMPLATE_ALREADY_INACTIVE",
   INVALID_TEMPLATE_EVENT: "INVALID_TEMPLATE_EVENT",
   TEMPLATE_NAME_IS_REQUIRED : "TEMPLATE_NAME_IS_REQUIRED",
   SUBJECT_REQUIRED : "SUBJECT_REQUIRED",
   BODY_REQUIRED : "BODY_REQUIRED",
   EMAIL_REQUIRED : "EMAIL_REQUIRED",
   ERROR_MESSAGE_REQUIRED : "ERROR_MESSAGE_REQUIRED",
   INVALID_EMAIL_LOG_STATE : "INVALID_EMAIL_LOG_STATE"

} as const;