export const ERROR_CODES = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  PASSWORD_RESET_NOT_ALLOWED: "PASSWORD_RESET_NOT_ALLOWED",
  INVALID_OTP: "INVALID_OTP",
  ROLE_REQUIRED: "ROLE_REQUIRED",
  GOOGLE_LOGIN_NOT_ALLOWED_FOR_ADMIN: "GOOGLE_LOGIN_NOT_ALLOWED_FOR_ADMIN",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  ROLE_MISMATCH: "ROLE_MISMATCH",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",


  INVALID_CURRENT_PASSWORD: "INVALID_CURRENT_PASSWORD",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
