export const departments = [
  "Engineering",
  "Software Development",
  "Frontend Engineering",
  "Backend Engineering",
  "Full Stack Engineering",
  "Mobile Development",
  "DevOps & Infrastructure",
  "Site Reliability Engineering (SRE)",
  "Cloud Engineering",
  "Platform Engineering",
  "QA & Testing",
  "Cybersecurity",
  "Information Technology (IT)",
  "IT Support",
  "Network Engineering",
  "Database Administration",
  "Embedded Systems",
  "Hardware Engineering",
  "R&D",
  "Data Science",
  "Data Engineering",
  "Data Analytics",
  "Business Intelligence",
  "Machine Learning",
  "Artificial Intelligence",
  "MLOps",
  "Product",
  "Product Management",
  "Product Operations",
  "Design",
  "UX Design",
  "UI Design",
  "UX Research",
  "Brand Design",
  "Motion Design",
  "Strategy",
  "Business Development",
  "Corporate Development",
  "Partnerships",
  "Mergers & Acquisitions",
  "Operations",
  "Business Operations",
  "Revenue Operations (RevOps)",
  "Sales",
  "Inside Sales",
  "Enterprise Sales",
  "Account Management",
  "Sales Operations",
  "Customer Success",
  "Marketing",
  "Growth Marketing",
  "Content Marketing",
  "Performance Marketing",
  "Brand Marketing",
  "Social Media",
  "Public Relations (PR)",
  "SEO",
  "Demand Generation",
  "Finance",
  "Accounting",
  "Financial Planning & Analysis (FP&A)",
  "Tax",
  "Treasury",
  "Audit & Risk",
  "Legal",
  "Compliance",
  "Intellectual Property",
  "HR",
  "Human Resources",
  "Talent Acquisition",
  "Recruiting",
  "Learning & Development",
  "People Operations",
  "Compensation & Benefits",
  "Diversity, Equity & Inclusion (DEI)",
  "Employee Experience",
  "Customer Support",
  "Customer Experience (CX)",
  "Technical Support",
  "Community",
  "Administration",
  "Executive",
  "Office Management",
  "Facilities",
  "Procurement",
  "Supply Chain",
  "Logistics",
  "Healthcare",
  "Clinical",
  "Research",
  "Education & Training",
  "Manufacturing",
  "Quality Assurance",
  "Regulatory Affairs",
  "Sustainability & ESG",
  "Communications",
  "Investor Relations",
];

export const skillSuggestions = [
  "React",
  "Next.js",
  "Vue.js",
  "Nuxt.js",
  "Angular",
  "Svelte",
  "SvelteKit",
  "Astro",
  "Remix",
  "HTML5",
  "CSS3",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Chakra UI",
  "shadcn/ui",
  "Radix UI",
  "Styled Components",
  "Sass/SCSS",
  "Webpack",
  "Vite",
  "Babel",
  "Storybook",
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C",
  "C++",
  "C#",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Ruby",
  "PHP",
  "Scala",
  "Elixir",
  "Haskell",
  "Dart",
  "R",
  "MATLAB",
  "Perl",
  "Lua",
  "Groovy",
  "Objective-C",
  "Shell Scripting",
  "Bash",
  "PowerShell",
  "Assembly",
  "COBOL",
  "Fortran",
  "Julia",
  "Clojure",
  "Erlang",
  "F#",
  "OCaml",
  "Prolog",
  "Solidity",
  "Node.js",
  "Express.js",
  "NestJS",
  "Fastify",
  "Django",
  "FastAPI",
  "Flask",
  "Spring Boot",
  "Spring MVC",
  "Ruby on Rails",
  "Laravel",
  "Symfony",
  "ASP.NET Core",
  ".NET",
  "Gin",
  "Fiber",
  "Phoenix",
  "Ktor",
  "Quarkus",
  "gRPC",
  "REST APIs",
  "GraphQL",
  "WebSockets",
  "tRPC",
  "Flutter",
  "React Native",
  "iOS Development",
  "Android Development",
  "SwiftUI",
  "Jetpack Compose",
  "Xamarin",
  "Ionic",
  "Expo",
  "Capacitor",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Microsoft SQL Server",
  "Oracle Database",
  "MariaDB",
  "MongoDB",
  "Redis",
  "Cassandra",
  "DynamoDB",
  "Firebase Firestore",
  "Neo4j",
  "Elasticsearch",
  "Snowflake",
  "Supabase",
  "CockroachDB",
  "InfluxDB",
  "AWS",
  "Google Cloud Platform (GCP)",
  "Microsoft Azure",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Pulumi",
  "Helm",
  "CI/CD",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "ArgoCD",
  "Nginx",
  "Linux",
  "Serverless",
  "Apache Spark",
  "Apache Kafka",
  "Apache Airflow",
  "Apache Flink",
  "Apache Hadoop",
  "dbt",
  "Snowflake",
  "Databricks",
  "Pandas",
  "Polars",
  "PySpark",
  "Fivetran",
  "Airbyte",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Reinforcement Learning",
  "Feature Engineering",
  "Statistical Modeling",
  "A/B Testing",
  "NumPy",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "XGBoost",
  "LightGBM",
  "Hugging Face Transformers",
  "LangChain",
  "MLflow",
  "Weights & Biases",
  "Prompt Engineering",
  "RAG",
  "Fine-tuning LLMs",
  "Vector Databases",
  "OpenAI API",
  "LLM Ops",
  "Pinecone",
  "Weaviate",
  "System Design",
  "Microservices",
  "Event-Driven Architecture",
  "Domain-Driven Design (DDD)",
  "CQRS",
  "Distributed Systems",
  "API Design",
  "Clean Architecture",
  "Design Patterns",
  "SOLID Principles",
  "Cybersecurity",
  "Penetration Testing",
  "OWASP",
  "OAuth 2.0",
  "JWT",
  "Zero Trust Security",
  "SOC 2",
  "GDPR Compliance",
  "HIPAA Compliance",
  "Cryptography",
  "Vulnerability Assessment",
  "Network Security",
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "Test-Driven Development (TDD)",
  "Behavior-Driven Development (BDD)",
  "Jest",
  "Cypress",
  "Playwright",
  "Selenium",
  "pytest",
  "JUnit",
  "Postman",
  "Load Testing",
  "Performance Testing",
  "Manual Testing",
  "Regression Testing",
  "UAT Testing",
  "Figma",
  "Adobe XD",
  "Sketch",
  "InVision",
  "Zeplin",
  "UX Research",
  "Wireframing",
  "Prototyping",
  "Design Systems",
  "Accessibility (WCAG)",
  "Responsive Design",
  "Motion Design",
  "Interaction Design",
  "Information Architecture",
  "User Testing",
  "Heuristic Evaluation",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Adobe InDesign",
  "Adobe After Effects",
  "Adobe Premiere Pro",
  "Canva",
  "Blender",
  "Cinema 4D",
  "3D Modeling",
  "Typography",
  "Color Theory",
  "Brand Identity",
  "Logo Design",
  "Print Design",
  "Packaging Design",
  "UI Animation",
  "Product Strategy",
  "Roadmap Planning",
  "User Story Writing",
  "Backlog Grooming",
  "Stakeholder Management",
  "OKRs",
  "KPIs",
  "Go-to-Market Strategy",
  "Competitive Analysis",
  "Market Research",
  "Product Analytics",
  "Feature Prioritization",
  "Product Discovery",
  "Customer Journey Mapping",
  "Jobs-to-be-Done (JTBD)",
  "PRD Writing",
  "Sprint Planning",
  "Release Management",
  "Beta Testing",
  "Voice of Customer (VoC)",
  "Agile",
  "Scrum",
  "Kanban",
  "SAFe",
  "Waterfall",
  "PRINCE2",
  "PMP",
  "Risk Management",
  "Change Management",
  "Resource Planning",
  "Budget Management",
  "Timeline Management",
  "Milestone Tracking",
  "Dependency Management",
  "Project Scheduling",
  "MS Project",
  "Jira",
  "Confluence",
  "Notion",
  "Linear",
  "Asana",
  "Trello",
  "ClickUp",
  "Monday.com",
  "Smartsheet",
  "Digital Marketing",
  "Content Marketing",
  "SEO",
  "SEM",
  "Google Ads",
  "Meta Ads",
  "LinkedIn Ads",
  "Email Marketing",
  "Marketing Automation",
  "HubSpot",
  "Marketo",
  "Mailchimp",
  "Social Media Marketing",
  "Influencer Marketing",
  "Affiliate Marketing",
  "Brand Strategy",
  "Copywriting",
  "Performance Marketing",
  "Growth Hacking",
  "Conversion Rate Optimization (CRO)",
  "Landing Page Optimization",
  "Demand Generation",
  "Account-Based Marketing (ABM)",
  "Public Relations (PR)",
  "Media Buying",
  "Programmatic Advertising",
  "Community Management",
  "Podcast Marketing",
  "Video Marketing",
  "YouTube SEO",
  "Google Analytics",
  "Google Tag Manager",
  "Mixpanel",
  "Amplitude",
  "Segment",
  "Customer Lifecycle Marketing",
  "Retention Marketing",
  "Word-of-Mouth Marketing",
  "Event Marketing",
  "Sponsorship Management",
  "B2B Sales",
  "B2C Sales",
  "Enterprise Sales",
  "Inside Sales",
  "Field Sales",
  "Cold Calling",
  "Cold Emailing",
  "Lead Generation",
  "Lead Qualification",
  "Prospecting",
  "Pipeline Management",
  "CRM Management",
  "Salesforce",
  "HubSpot CRM",
  "Zoho CRM",
  "Account Management",
  "Key Account Management",
  "Channel Sales",
  "Partner Sales",
  "Solution Selling",
  "Consultative Selling",
  "SPIN Selling",
  "MEDDIC",
  "Challenger Sale",
  "Negotiation",
  "Closing Techniques",
  "Upselling",
  "Cross-selling",
  "Sales Forecasting",
  "Quota Management",
  "Contract Negotiation",
  "Proposal Writing",
  "RFP Responses",
  "Demo Delivery",
  "Sales Enablement",
  "Revenue Operations (RevOps)",
  "Customer Success Management",
  "Onboarding",
  "Churn Reduction",
  "NPS Management",
  "CSAT Management",
  "Customer Retention",
  "Renewal Management",
  "Escalation Management",
  "Help Desk Management",
  "Zendesk",
  "Intercom",
  "Freshdesk",
  "ServiceNow",
  "Live Chat Support",
  "Technical Support",
  "Customer Training",
  "Knowledge Base Management",
  "SLA Management",
  "Ticket Management",
  "Financial Modeling",
  "Financial Analysis",
  "Financial Reporting",
  "Budgeting",
  "Forecasting",
  "Variance Analysis",
  "Management Accounting",
  "Cost Accounting",
  "Revenue Recognition",
  "Accounts Payable",
  "Accounts Receivable",
  "General Ledger",
  "Month-End Close",
  "Year-End Close",
  "Audit",
  "Internal Audit",
  "External Audit",
  "Tax Planning",
  "Tax Compliance",
  "GST/VAT",
  "Transfer Pricing",
  "Treasury Management",
  "Cash Flow Management",
  "Working Capital Management",
  "Investment Analysis",
  "Valuation",
  "DCF Analysis",
  "M&A",
  "Due Diligence",
  "Equity Research",
  "Fixed Income",
  "Derivatives",
  "Portfolio Management",
  "Risk Management",
  "IFRS",
  "GAAP",
  "QuickBooks",
  "SAP FICO",
  "Oracle Financials",
  "Tally",
  "Xero",
  "Bloomberg Terminal",
  "Excel Financial Modeling",
  "Talent Acquisition",
  "Full-Cycle Recruiting",
  "Technical Recruiting",
  "Executive Search",
  "Campus Hiring",
  "Bulk Hiring",
  "Employer Branding",
  "Job Description Writing",
  "Interview Coordination",
  "Behavioral Interviewing",
  "Competency-Based Interviewing",
  "Offer Negotiation",
  "Background Verification",
  "Onboarding",
  "HR Operations",
  "HRIS Management",
  "Workday",
  "BambooHR",
  "SAP SuccessFactors",
  "Darwinbox",
  "Payroll Management",
  "Compensation & Benefits",
  "Job Evaluation",
  "Salary Benchmarking",
  "Performance Management",
  "OKR Facilitation",
  "360-Degree Feedback",
  "Learning & Development",
  "Training Needs Analysis",
  "Instructional Design",
  "Leadership Development",
  "Succession Planning",
  "Employee Engagement",
  "Culture Building",
  "Diversity, Equity & Inclusion (DEI)",
  "HR Business Partnering",
  "Labor Law Compliance",
  "Grievance Handling",
  "Disciplinary Procedures",
  "HR Analytics",
  "Workforce Planning",
  "Organizational Design",
  "Contract Drafting",
  "Contract Review",
  "Contract Negotiation",
  "Corporate Law",
  "Commercial Law",
  "Employment Law",
  "Intellectual Property Law",
  "Patent Filing",
  "Trademark Registration",
  "Data Privacy Law",
  "GDPR",
  "CCPA",
  "Regulatory Compliance",
  "Anti-Money Laundering (AML)",
  "Know Your Customer (KYC)",
  "Litigation Management",
  "Arbitration",
  "Legal Research",
  "Legal Writing",
  "Board Governance",
  "Shareholder Agreements",
  "Due Diligence",
  "Mergers & Acquisitions (Legal)",
  "Venture Capital Agreements",
  "Term Sheets",
  "SEBI Compliance",
  "RBI Compliance",
  "Operations Management",
  "Process Improvement",
  "Lean Management",
  "Six Sigma",
  "Kaizen",
  "5S Methodology",
  "Standard Operating Procedures (SOPs)",
  "Supply Chain Management",
  "Procurement",
  "Vendor Management",
  "Vendor Negotiations",
  "Inventory Management",
  "Warehouse Management",
  "Logistics",
  "Last-Mile Delivery",
  "Import/Export",
  "Customs Compliance",
  "Demand Planning",
  "Forecasting",
  "ERP Systems",
  "SAP SCM",
  "Oracle SCM",
  "Quality Management",
  "ISO 9001",
  "ISO 27001",
  "FMEA",
  "Root Cause Analysis",
  "Business Continuity Planning",
  "Facilities Management",
  "SQL",
  "Advanced Excel",
  "Power BI",
  "Tableau",
  "Looker",
  "Metabase",
  "Google Data Studio",
  "Qlik",
  "Data Visualization",
  "Dashboard Design",
  "Business Analysis",
  "Requirements Gathering",
  "Gap Analysis",
  "Process Mapping",
  "SWOT Analysis",
  "Data Storytelling",
  "Cohort Analysis",
  "Funnel Analysis",
  "Attribution Modeling",
  "Content Writing",
  "Technical Writing",
  "Copywriting",
  "Ghostwriting",
  "Scriptwriting",
  "Blog Writing",
  "White Paper Writing",
  "Case Study Writing",
  "Grant Writing",
  "Proposal Writing",
  "Editing & Proofreading",
  "SEO Writing",
  "UX Writing",
  "Microcopy",
  "Social Media Content",
  "Email Copywriting",
  "Press Release Writing",
  "Journalism",
  "Storytelling",
  "Presentation Design",
  "Public Speaking",
  "Speechwriting",
  "Internal Communications",
  "Crisis Communications",
  "Executive Communications",
  "Thought Leadership",
  "Curriculum Design",
  "Instructional Design",
  "E-Learning Development",
  "LMS Administration",
  "Classroom Training",
  "Facilitation",
  "Coaching",
  "Mentoring",
  "Academic Research",
  "Pedagogy",
  "Assessment Design",
  "SCORM",
  "Articulate 360",
  "Adobe Captivate",
  "Educational Technology",
  "K-12 Education",
  "Higher Education",
  "Corporate Training",
  "Training Evaluation",
  "Clinical Research",
  "Clinical Trials",
  "Pharmacovigilance",
  "Regulatory Affairs",
  "Medical Writing",
  "GCP Compliance",
  "GMP Compliance",
  "Healthcare Administration",
  "Hospital Operations",
  "Electronic Health Records (EHR)",
  "Medical Coding",
  "Medical Billing",
  "HIPAA Compliance",
  "Patient Care",
  "Nursing",
  "Pharmacy",
  "Public Health",
  "Epidemiology",
  "Biostatistics",
  "Healthcare Analytics",
  "Telemedicine",
  "Medical Devices",
  "Quality Assurance (Pharma)",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Civil Engineering",
  "Structural Engineering",
  "Chemical Engineering",
  "Industrial Engineering",
  "Aerospace Engineering",
  "Automotive Engineering",
  "Manufacturing Engineering",
  "Process Engineering",
  "Environmental Engineering",
  "Biomedical Engineering",
  "Materials Engineering",
  "AutoCAD",
  "SolidWorks",
  "CATIA",
  "ANSYS",
  "MATLAB Simulink",
  "PLC Programming",
  "SCADA",
  "PCB Design",
  "Embedded Systems",
  "IoT",
  "Robotics",
  "Automation",
  "CNC Machining",
  "Welding",
  "Thermodynamics",
  "Fluid Mechanics",
  "Architecture",
  "Interior Design",
  "Urban Planning",
  "Landscape Architecture",
  "BIM (Building Information Modeling)",
  "Revit",
  "SketchUp",
  "AutoCAD Architecture",
  "Construction Management",
  "Project Estimation",
  "Quantity Surveying",
  "Real Estate Sales",
  "Property Management",
  "Real Estate Valuation",
  "Lease Management",
  "RERA Compliance",
  "Site Supervision",
  "Facility Management",
  "Market Research",
  "Qualitative Research",
  "Quantitative Research",
  "Primary Research",
  "Secondary Research",
  "Consumer Insights",
  "Competitive Intelligence",
  "Industry Analysis",
  "Business Strategy",
  "Corporate Strategy",
  "Growth Strategy",
  "Innovation Management",
  "Design Thinking",
  "Systems Thinking",
  "Scenario Planning",
  "Strategic Planning",
  "Consulting",
  "Management Consulting",
  "Business Case Development",
  "Feasibility Studies",
  "Fundraising",
  "Venture Capital",
  "Angel Investment",
  "Pitch Deck Creation",
  "Investor Relations",
  "Startup Operations",
  "Business Development",
  "Partnership Development",
  "Product-Market Fit",
  "Unit Economics",
  "Cap Table Management",
  "ESOP Management",
  "Startup Scaling",
  "Zero-to-One Building",
  "Revenue Modeling",
  "Leadership",
  "Team Management",
  "People Management",
  "Conflict Resolution",
  "Decision Making",
  "Critical Thinking",
  "Problem Solving",
  "Analytical Thinking",
  "Communication",
  "Interpersonal Skills",
  "Emotional Intelligence (EQ)",
  "Empathy",
  "Active Listening",
  "Negotiation",
  "Persuasion",
  "Influencing",
  "Collaboration",
  "Cross-functional Teamwork",
  "Adaptability",
  "Resilience",
  "Time Management",
  "Prioritization",
  "Self-Motivation",
  "Accountability",
  "Attention to Detail",
  "Creativity",
  "Innovation",
  "Growth Mindset",
  "Continuous Learning",
  "Mentoring",
  "Coaching",
  "Delegation",
  "Executive Presence",
  "Strategic Thinking",
  "Networking",
  "Relationship Building",
  "Cultural Sensitivity",
  "Remote Work",
  "Async Communication",
  "English",
  "Hindi",
  "Tamil",
  "Telugu",
  "Kannada",
  "Malayalam",
  "Marathi",
  "Bengali",
  "Gujarati",
  "Punjabi",
  "Mandarin Chinese",
  "Spanish",
  "French",
  "German",
  "Arabic",
  "Japanese",
  "Korean",
  "Portuguese",
  "Russian",
  "Italian",
  "Dutch",
  "Turkish",
  "Indonesian",
  "Swahili",
  "Microsoft Office",
  "Google Workspace",
  "Slack",
  "Microsoft Teams",
  "Zoom",
  "Miro",
  "Loom",
  "Airtable",
  "Zapier",
  "Make (Integromat)",
  "Calendly",
  "Typeform",
  "Webflow",
  "WordPress",
  "Shopify",
  "Salesforce",
  "SAP",
  "Oracle ERP",
  "Tally",
  "Zoho Suite",
  "ChatGPT",
  "Midjourney",
  "Video Editing",
  "Adobe Premiere Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "Motion Graphics",
  "Adobe After Effects",
  "Color Grading",
  "Sound Design",
  "Podcast Production",
  "Photography",
  "Videography",
  "Drone Filming",
  "Storyboarding",
  "Scriptwriting",
  "Film Direction",
  "Production Management",
  "Casting",
  "Talent Management",
  "Music Production",
  "Audio Mixing",
  "Audio Mastering",
  "E-Commerce Management",
  "Amazon Seller Central",
  "Flipkart Seller Hub",
  "Shopify Development",
  "WooCommerce",
  "Marketplace Management",
  "Category Management",
  "Merchandising",
  "Pricing Strategy",
  "Inventory Forecasting",
  "Returns Management",
  "Customer Acquisition",
  "Loyalty Programs",
  "Retail Operations",
  "Store Management",
  "Visual Merchandising",
  "FMCG Sales",
  "Trade Marketing",
  "Distribution Management",
];