export enum EmailEvent {
  JOB_APPLIED = "JOB_APPLIED",
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  SELECTED = "SELECTED",
  REJECTED = "REJECTED",
  ACCOUNT_CREATED = "ACCOUNT_CREATED",
  SUBSCRIPTION_PURCHASED = "SUBSCRIPTION_PURCHASED",
  SUBSCRIPTION_EXPIRING = "SUBSCRIPTION_EXPIRING",
  SUBSCRIPTION_EXPIRED = "SUBSCRIPTION_EXPIRED",
  INTERVIEW_RESCHEDULED = "INTERVIEW_RESCHEDULED",
  INTERVIEW_RESCHEDULE_REQUEST_REJECTED = "INTERVIEW_RESCHEDULE_REQUEST_REJECTED",
  INTERVIEW_RESCHEDULE_REQUEST_APPROVED = "INTERVIEW_RESCHEDULE_REQUEST_APPROVED",
  
}
