export const SUCCESS_MESSAGES = {
  APPLICATION_LOADED_SUCCESSFULLY: "Applications loaded successfully",
  ACTIVITY_LOG_LOADED_SUCCESSFULLY: "Activity log loaded successfully",
  CANDIDATE_PROFILE_LOADED_SUCCESSFULLY:
    "Candidate profile loaded successfully",
  CANDIDATES_LISTED_SUCCESSFULLY: "Candidates listed successfully",
  RECRUITER_PROFILE_LOADED_SUCCESSFULLY:
    "Recruiter profile loaded successfully",
  RECRUITERS_LOADED_SUCCESSFULLY: "Recruiters loaded successfully",
  CANDIDATE_REJECTED_SUCCESSFULLY: "Candidate rejected successfully",
  RECRUITER_VERIFIED_SUCCESSFULLY: "Recruiter verified successfully",
  SUBSCRIPTION_PLAN_CREATED_SUCCESSFULLY:
    "Subscription plan created successfully",
  PLAN_LOADED_SUCCESSFULLY: "Plan loaded successfully",
  SUBSCRIPTION_PLANS_FETCHED_SUCCESSFULLY:
    "Subscription plans fetched successfully",
  SUBSCRIPTION_PLAN_HIDDEN_SUCCESSFULLY:
    "Subscription plan hidden successfully",
  SUBSCRIPTION_PLAN_UNHIDDEN_SUCCESSFULLY:
    "Subscription plan unhidden successfully",
  SUBSCRIPTION_PLAN_UPDATED_SUCCESSFULLY:
    "Subscription plan updated successfully",
  USER_BLOCKED_SUCCESSFULLY: "User blocked successfully",
  USER_UNBLOCKED_SUCCESSFULLY: "User unblocked successfully",
  ADMIN_LOGIN_SUCCESSFULLY: "Admin login successful",
  LOGIN_SUCCESSFULLY: "Login successful",
  LOGOUT_SUCCESSFULLY: "Logout successful",
  EMAIL_UPDATE_NOT_ALLOWED_FOR_THIS_ROLE:
    "Email update not allowed for this role",
  PASSWORD_RESET_EMAIL_SENT: "Password reset email sent",
  PASSWORD_RESET_SUCCESSFULLY: "Password reset successfully",
  GOOGLE_LOGIN_SUCCESSFULLY: "Google login successful",
  OTP_SENT_SUCCESSFULLY: "OTP sent successfully",
  FILE_IS_REQUIRED: "File is required",
  PROFILE_IMAGE_UPDATED_SUCCESSFULLY: "Profile image updated successfully",
  USER_REGISTERED_SUCCESSFULLY: "User registered successfully",
  PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
  PROFILE_COMPLETED_SUCCESSFULLY: "Profile completed successfully",
  PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully",
  EMAIL_TEMPLATE_CREATED_SUCCESSFULLY: "Email template created successfully",
  TEMPLATE_DELETED_SUCCESSFULLY: "Template deleted successfully",
  EMAIL_TEMPLATES_LISTED_SUCCESSFULLY: "Email templates listed successfully",
  TEST_EMAIL_SENT_SUCCESSFULLY: "Test email sent successfully",
  EMAIL_TEMPLATE_STATUS_UPDATED: "Email template status updated",
  TEMPLATE_UPDATED_SUCCESSFULLY: "Template updated successfully",
  EMAIL_LOGS_LOADED_SUCCESSFULLY: "Email logs loaded successfully",
  JOB_APPLICATION_SUBMITTED_SUCCESSFULLY:
    "Job application submitted successfully",
  APPLICATIONS_FETCHED_SUCCESSFULLY: "Applications fetched successfully",
  MESSAGE_DELETED_SUCCESSFULLY: "Message deleted successfully",
  NOTIFICATIONS_FETCHED_SUCCESSFULLY: "Notifications fetched successfully",
  UNREAD_NOTIFICATION_COUNT_FETCHED_SUCCESSFULLY:
    "Unread notification count fetched successfully",
  ALL_NOTIFICATIONS_MARKED_AS_READ: "All notifications marked as read",
  NOTIFICATION_MARKED_AS_READ: "Notification marked as read",
  RESUME_DELETED_SUCCESSFULLY: "Resume deleted successfully",
  RESUME_DOWNLOADED_SUCCESSFULLY: "Resume downloaded successfully",
  RESUME_LOADED_SUCCESSFULLY: "Resume loaded successfully",
  RESUME_PARSED_SUCCESSFULLY: "Resume parsed successfully",
  RESUME_UPLOADED_SUCCESSFULLY: "Resume uploaded successfully",
  SUBSCRIBERS_FETCHED_SUCCESSFULLY: "Subscribers fetched successfully",
  PLAN_HIDDEN_SUCCESSFULLY: "Plan hidden successfully",
  PLAN_DEACTIVATED_SUCCESSFULLY: "Plan deactivated successfully",
  SUBSCRIPTION_CANCELLED: "Subscription cancelled",
  PAYMENT_ORDER_CREATED_SUCCESSFULLY: "Payment order created successfully",
  PLAN_DETAILS_FETCHED_SUCCESSFULLY: "Plan details fetched successfully",
  CURRENT_SUBSCRIPTION_FETCHED_SUCCESSFULLY:
    "Current subscription fetched successfully",
  SUBSCRIPTION_RENEWED_SUCCESSFULLY: "Subscription renewed successfully",
  SUBSCRIPTION_UPGRADED_SUCCESSFULLY: "Subscription upgraded successfully",
  PAYMENT_VERIFIED_SUCCESSFULLY: "Payment verified successfully",
  JOB_LISTED_SUCCESSFULLY: "Jobs listed successfully",
  JOB_POST_LOADED_SUCCESSFULLY: "Job post loaded successfully",
  JOB_BLOCKED_SUCCESSFULLY: "Job blocked successfully",
  JOB_UNBLOCKED_SUCCESSFULLY: "Job unblocked successfully",
  JOB_CREATED_SUCCESSFULLY: "Job created successfully",
  JOB_DELETED_SUCCESSFULLY: "Job deleted succesfully",
  JOB_PUBLISH_SUCCESSFULLY: "Job published successfully",
  JOB_UNHIDE_SUCCESSFULLY: "Job unhide successfully",
  JOB_HIDE_SUCCESSFULLY: "Job hide successfully",
  JOB_POST_UPDATED_SUCCESSFULLY: "Job post updated successfully",
  ADMIN_LOGIN_SUCCESFULLY: "Admin login succesfully",
  INTERVIEW_SCHEDULED_SUCCESSFULLY: "Interview scheduled successfully",
  APPLICATION_STATUS_UPDATED_SUCCESSFULLY:
    "Application status updated successfully",
  INTERVIEWS_FETCHED_SUCCESSFULLY: "INTERVIEWS_FETCHED_SUCCESSFULLY",
  INTERVIEW_FETCHED_SUCCESSFULLY: "Interview Fetched successfully",
  INTERVIEW_CANCELLED_SUCCESSFULLY : "Interview cancelled succesfully",
  INTERVIEW_COMPLETED_SUCCESSFULLY : "Interview completed succesfully",
  INTERVIEW_STARTED_SUCCESSFULLY : "Interview started succesfully",
  INTERVIEW_RESCHEDULED_SUCCESSFULLY : "Interview Rescheduled successfully",
  RECRUITER_JOINED_INTERVIEW_SUCCESSFULLY : "Recruiter joined interview successfully",
  CANDIDATE_JOINED_INTERVIEW_SUCCESSFULLY : "Candidate joined interview successfully",
  CANDIDATE_INTERVIEWS_LOADED_SUCCESSFULLY : "Candidate interview loaded successfully",
  CANDIDATE_INTERVIEW_DETAIL_FETCHED_SUCCESSFULLY : "Candidate interview detail fetched successfully",
  INTERVIEW_ACCEPTED_SUCCESSFULLY : "Interview accepted successfully",
  INTERVIEW_REJECTED_SUCCESSFULLY : "Interview rejected successfully",
  INTERVIEW_RESCHEDULE_REQUESTED_SUCCESSFULLY : "Interview Reschedule request successfully",
  RESCHEDULED_REQUEST_ACCEPTED_SUCCESSFULLY : "Rescheduled request accepted successfully",
  RESCHEDULED_REQUEST_REJECTED_SUCCESSFULLY :  "Rescheduled request rejected successfully",
  OTP_SENT_TO_NEW_EMAIL : "Otp sent to new Email",
  EMAIL_UPDATED_SUCCESSFULLY : "Email updated successfully",
  ACCESS_TOKEN_REFRESHED_SUCCESSFULLY : "Access token refreshed successfully",
  JOB_DETAILS_LOADED_SUCCESSFULLY : "Job details loaded successfully",
  PLAN_ACTIVATED_SUCCESSFULLY : "Plan activated successfully",
  INTERVIEW_NOTES_UPDATED : "Interview noted updated",
  HIRING_DECISION_DATA_FETCHED_SUCCESSFULLY : "Hiring decision data fetched successfully",
} as const;
