export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  OTP_EXPIRED: "OTP_EXPIRED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",
} as const;

export type ErrorCode =
  typeof ERROR_CODES[keyof typeof ERROR_CODES];
