export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS : "USER_ALREADY_EXISTS",
  UNAUTHORIZED : "UNAUTHORIZED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  OTP_EXPIRED: "OTP_EXPIRED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  UNAUTHORIZED_ACCESS: "UNAUTHORIZED_ACCESS",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
  ROLE_REQUIRED : "ROLE_REQUIRED",
  GOOGLE_LOGIN_NOT_ALLOWED_FOR_ADMIN : "GOOGLE_LOGIN_NOT_ALLOWED_FOR_ADMIN",
  ROLE_MISMATCH : "ROLE_MISMATCH",
  PASSWORD_RESET_NOT_ALLOWED : "PASSWORD_RESET_NOT_ALLOWED",
  ADMIN_LOGIN_NOT_ALLOWED : "ADMIN_LOGIN_NOT_ALLOWED",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",
  UNSUPPORTED_ROLE : "UNSUPPORTED_ROLE",
  USER_ID_NOT_FOUND : "USER_ID_NOT_FOUND"
} as const;

export type ErrorCode =
  typeof ERROR_CODES[keyof typeof ERROR_CODES];
