export const SUCCESS_CODES = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  USER_CREATED: "USER_CREATED",
  PASSWORD_RESET_LINK_SENT: "PASSWORD_RESET_LINK_SENT",
  PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
  OTP_SENT: "OTP_SENT",
  OTP_VERIFIED: "OTP_VERIFIED",
} as const;

export type SuccessCode =
  typeof SUCCESS_CODES[keyof typeof SUCCESS_CODES];
