export const SocketEvents = {
  CONNECTION: "connection",
  DISCONNECT: "disconnect",
  JOIN_ROOM: "join-room",
  LEAVE_ROOM: "leave-room",
  ROOM_JOINED: "room-joined",
  JOIN_ROOM_ERROR: "join-room-error",
  USER_JOINED: "user-joined",
  USER_LEFT: "user-left",
  OFFER: "offer",
  ANSWER: "answer",
  ICE_CANDIDATE: "ice-candidate",
  CHAT_MESSAGE: "chat-message",
  END_INTERVIEW: "interview-ended",
} as const;
