export const ActivityAction = {
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  PASSWORD_UPDATED: "PASSWORD_UPDATED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",

  JOB_POSTED: "JOB_POSTED",
  JOB_UPDATED: "JOB_UPDATED",
  JOB_DELETED: "JOB_DELETED",

  SUBSCRIPTION_CREATED: "SUBSCRIPTION_CREATED",
  SUBSCRIPTION_UPDATED: "SUBSCRIPTION_UPDATED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",

  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_RESCHEDULED: "INTERVIEW_RESCHEDULED",

  CANDIDATE_SELECTED: "CANDIDATE_SELECTED",
  CANDIDATE_REJECTED: "CANDIDATE_REJECTED",
} as const;

export type ActivityActionType =
  typeof ActivityAction[keyof typeof ActivityAction];

  