export const ERROR_CODES = {
  USER_NOT_FOUND : "USER_NOT_FOUND",
  RECRUITER_PROFILE_NOT_FOUND : "RECRUITER_PROFILE_NOT_FOUND",
  RECRUITER_CANNOT_BE_REJECTED : "RECRUITER_CANNOT_BE_REJECTED",
  RECRUITER_CANNOT_BE_VERIFIED : "RECRUITER_CANNOT_BE_VERIFIED"
} as const;

export type ErrorCode =
  typeof ERROR_CODES[keyof typeof ERROR_CODES];
