export const ERROR_CODES = {
  USER_NOT_FOUND : "USER_NOT_FOUND",
  RECRUITER_PROFILE_NOT_FOUND : "RECRUITER_PROFILE_NOT_FOUND",
  RECRUITER_CANNOT_BE_REJECTED : "RECRUITER_CANNOT_BE_REJECTED",
  RECRUITER_CANNOT_BE_VERIFIED : "RECRUITER_CANNOT_BE_VERIFIED",
  EMAIL_TEMPLATE_NOT_FOUND : 'EMAIL_TEMPLATE_NOT_FOUND',
  EMAIL_TEMPLATE_IS_NOT_ACTIVE: "EMAIL_TEMPLATE_IS_NOT_ACTIVE",
  JOB_POST_NOT_FOUND : "JOB_POST_NOT_FOUND",
  JOB_POST_ID_NOT_FOUND : "JOB_POST_ID_NOT_FOUND",
  JOB_POST_ALREADY_BLOCKED : "JOB_POST_ALREADY_BLOCKED",
  JOB_POST_IS_NOT_BLOCKED : "JOB_POST_IS_NOT_BLOCKED",
  PLAN_NOT_FOUND : "PLAN_NOT_FOUND",
  RAZORPAY_PLAN_ID_REQUIRED : "RAZORPAY_PLAN_ID_REQUIRED",
  PLAN_ALREADY_EXISTS  : "PLAN_ALREADY_EXISTS",
  INVALID_BILLING_INTERVAL : "INVALID_BILLING_INTERVAL",
  INVALID_PRICE : "INVALID_PRICE",
  INVALID_PLAN_NAME : "INVALID_PLAN_NAME"

} as const;

export type ErrorCode =
  typeof ERROR_CODES[keyof typeof ERROR_CODES];