export const CANDIDATE_ERROR = {
  USER_ID_IS_REQUIRED: "USER_ID_IS_REQUIRED",
  EXPERIENCE_YEARS_CANNOT_BE_NEGATIVE: "EXPERIENCE_YEARS_CANNOT_BE_NEGATIVE",
  PROFILE_CANNOT_BE_COMPLETED: "PROFILE_CANNOT_BE_COMPLETED",
  CURRENT_JOB_CANNOT_BE_EMPTY: "CURRENT_JOB_CANNOT_BE_EMPTY",
  AT_LEAST_ONE_SKILL_IS_REQUIRED: "AT_LEAST_ONE_SKILL_IS_REQUIRED",
  EDUCATION_LEVEL_CANNOT_BE_EMPTY: "EDUCATION_LEVEL_CANNOT_BE_EMPTY",
  AT_LEAST_ONE_LOCATION_IS_REQUIRED: "AT_LEAST_ONE_LOCATION_IS_REQUIRED",
  BIO_EXCEEDS_MAX_LENGTH: "BIO_EXCEEDS_MAX_LENGTH",
  INVALID_LINKEDIN_URL: "INVALID_LINKEDIN_URL",
  INVALID_PORTFOLIO_URL: "INVALID_PORTFOLIO_URL",
} as const;

export type ErrorCode = (typeof CANDIDATE_ERROR)[keyof typeof CANDIDATE_ERROR];