export const USER_ERROR = {
  FULL_NAME_IS_REQUIRED: "FULL_NAME_IS_REQUIRED",
  FULL_NAME_CANNOT_BE_EMPTY: "FULL_NAME_CANNOT_BE_EMPTY",
  INVALID_PROFILE_IMAGE_URL: "INVALID_PROFILE_IMAGE_URL",
} as const;

export type UserErrorCode = (typeof USER_ERROR)[keyof typeof USER_ERROR];