export const RESUME_ERROR = {
RESUME_ALREADY_INACTIVE :"RESUME_ALREADY_INACTIVE",
RESUME_ALREADY_ACTIVE : "RESUME_ALREADY_ACTIVE",
RESUME_NOT_ACTIVE : "RESUME_NOT_ACTIVE",

  } as const;

export type ErrorCode = (typeof RESUME_ERROR)[keyof typeof RESUME_ERROR];
