import type { EVENTS } from "./templateEvents";

export const EmailEvent = {
  ACCOUNT_CREATED: "ACCOUNT_CREATED",
  JOB_APPLIED: "JOB_APPLIED",
  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_RESCHEDULED: "INTERVIEW_RESCHEDULED",
  INTERVIEW_RESCHEDULE_REQUEST_REJECTED:
    "INTERVIEW_RESCHEDULE_REQUEST_REJECTED",
  SELECTED: "SELECTED",
  REJECTED: "REJECTED",
  SUBSCRIPTION_PURCHASED: "SUBSCRIPTION_PURCHASED",
  SUBSCRIPTION_EXPIRING: "SUBSCRIPTION_EXPIRING",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
} as const;

export type EmailEvent =
  (typeof EmailEvent)[keyof typeof EmailEvent];

export type EventValue = (typeof EVENTS)[number]["value"];