export const ERROR_CODES = {
    INVALUD_CREDENTIALS : "INVALID_CREDENTIALS",
    USER_NOT_FOUND : "USER_NOT_FOUND",
    USER_ALREADY_EXISTS : "USER_ALREADY_REGISTER",
    EMAIL_ALREADY_EXISTS : "EMAIL_ALREADY_EXISTS",
    RECRUITER_PROFILE_NOT_FOUND : "RECRUITER_PROFILE_NOT_FOUND"
}


export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];