export const DOMAIN_ERRORS = {
   ACTIVITY_ACTION_REQUIRED : "ACTIVITY_ACTION_REQUIRED",
   USER_ID_REQUIRED : "USER_ID_REQUIRED",
   ACTIVITY_ID_REQUIRED : "ACTIVITY_ID_REQUIRED",
   ENTITY_TYPE_REQUIRED : "ENTITY_TYPE_REQUIRED",
   ENTITY_ID_REQUIRED : "ENTITY_ID_REQUIRED",
} as const;