export const ERROR_CODES = {
  USER_NOT_FOUND : "USER_NOT_FOUND",
  RECRUITER_PROFILE_NOT_FOUND : "RECRUITER_PROFILE_NOT_FOUND",
  RECRUITER_CANNOT_BE_REJECTED : "RECRUITER_CANNOT_BE_REJECTED",
  RECRUITER_CANNOT_BE_VERIFIED : "RECRUITER_CANNOT_BE_VERIFIED",
  EMAIL_TEMPLATE_NOT_FOUND : 'EMAIL_TEMPLATE_NOT_FOUND',
  EMAIL_TEMPLATE_IS_NOT_ACTIVE: "EMAIL_TEMPLATE_IS_NOT_ACTIVE",
  PLAN_ALREADY_EXISTS : "PLAN_ALREADY_EXISTS",
  PLAN_ALREADY_INACTIVE : "PLAN_ALREADY_INACTIVE",
  PLAN_ALREADY_ACTIVE : "PLAN_ALREADY_ACTIVE",
  JOB_POST_NOT_FOUND : "JOB_POST_NOT_FOUND",
 UNAUTHORIZED_ACTION : "UNAUTHORIZED_ACTION",
 PLAN_NOT_FOUND : "PLAN_NOT_FOUND",
 SUBSCRIPTION_ALREADY_EXISTS : "SUBSCRIPTION_ALREADY_EXISTS",
 SUBSCRIPTION_NOT_FOUND : "SUBSCRIPTION_NOT_FOUND",
 ACTIVE_SUBSCRIPTION_ALREADY_EXISTS : "ACTIVE_SUBSCRIPTION_ALREADY_EXISTS",
 FREE_PLAN_DOES_NOT_REQUIRE_PAYMENT : "FREE_PLAN_DOES_NOT_REQUIRE_PAYMENT",
 
} as const;

export type ErrorCode =
  typeof ERROR_CODES[keyof typeof ERROR_CODES];

 