export const ERROR_CODES = {
 EMAIL_TEMPLATE_EXISTS : "EMAIL_TEMPLATE_EXISTS",
 EMAIL_TEMPLATE_NOT_FOUND : "EMAIL_TEMPLATE_NOT_FOUND",
 EMAIL_TEMPLATE_IS_NOT_ACTIVE : "EMAIL_TEMPLATE_IS_NOT_ACTIVE"
 
} as const;

export type ErrorCode =
  typeof ERROR_CODES[keyof typeof ERROR_CODES];

 